using System.Text;

namespace StringThing.Aot.Generator;

internal static class RowSourceWriter
{
    private const string InterfaceFullName = "global::StringThing.Aot.IStringThingRow";
    private const string ReaderFullName = "global::System.Data.Common.DbDataReader";
    private const string ReadOnlySpanFullName = "global::System.ReadOnlySpan";

    public static string Write(RowModel model)
    {
        var fullyQualifiedSelf = $"global::{model.FullyQualifiedTypeName}";
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var hasNamespace = model.Namespace.Length > 0;
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine();
            builder.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : string.Empty;

        builder.Append(indent).Append("partial ").Append(model.TypeKindKeyword).Append(' ').Append(model.TypeName)
            .Append(" : ").Append(InterfaceFullName).Append('<').Append(fullyQualifiedSelf).AppendLine(">");
        builder.Append(indent).AppendLine("{");

        var memberIndent = indent + "    ";

        builder.Append(memberIndent)
            .Append("private static readonly string[] __stringThingColumnBindingOrder = new string[] { ");
        for (var i = 0; i < model.Columns.Count; i++)
        {
            if (i > 0) builder.Append(", ");
            builder.Append('"').Append(EscapeStringLiteral(model.Columns[i].ColumnName)).Append('"');
        }
        builder.AppendLine(" };");

        builder.AppendLine();
        builder.Append(memberIndent)
            .Append("static ").Append(ReadOnlySpanFullName).Append("<string> ")
            .Append(InterfaceFullName).Append('<').Append(fullyQualifiedSelf).Append(">.ColumnBindingOrder")
            .AppendLine(" => __stringThingColumnBindingOrder;");

        builder.AppendLine();
        builder.Append(memberIndent)
            .Append("static ").Append(fullyQualifiedSelf).Append(' ')
            .Append(InterfaceFullName).Append('<').Append(fullyQualifiedSelf).Append(">.Read(")
            .Append(ReaderFullName).Append(" reader, ").Append(ReadOnlySpanFullName).Append("<int> ordinals)");
        builder.AppendLine();

        WriteReadBody(builder, model, memberIndent, fullyQualifiedSelf);

        builder.Append(indent).AppendLine("}");

        if (hasNamespace)
            builder.AppendLine("}");

        return builder.ToString();
    }

    private static void WriteReadBody(StringBuilder builder, RowModel model, string memberIndent, string fullyQualifiedSelf)
    {
        var bodyIndent = memberIndent + "    ";
        var readIndent = bodyIndent + "    ";

        builder.Append(memberIndent).AppendLine("{");

        if (model.Construction == ConstructionStrategy.Constructor)
        {
            builder.Append(bodyIndent).Append("return new ").Append(fullyQualifiedSelf).AppendLine("(");
            for (var i = 0; i < model.Columns.Count; i++)
            {
                var isLast = i == model.Columns.Count - 1;
                builder.Append(readIndent);
                WriteColumnRead(builder, model.Columns[i], i);
                builder.AppendLine(isLast ? ");" : ",");
            }
        }
        else
        {
            builder.Append(bodyIndent).Append("return new ").Append(fullyQualifiedSelf).AppendLine();
            builder.Append(bodyIndent).AppendLine("{");
            for (var i = 0; i < model.Columns.Count; i++)
            {
                var isLast = i == model.Columns.Count - 1;
                builder.Append(readIndent).Append(model.Columns[i].MemberName).Append(" = ");
                WriteColumnRead(builder, model.Columns[i], i);
                builder.AppendLine(isLast ? "," : ",");
            }
            builder.Append(bodyIndent).AppendLine("};");
        }

        builder.Append(memberIndent).AppendLine("}");
    }

    private static void WriteColumnRead(StringBuilder builder, RowColumn column, int ordinalIndex)
    {
        if (column.IsNullable)
        {
            builder.Append("reader.IsDBNull(ordinals[").Append(ordinalIndex).Append("]) ? default(")
                .Append(column.FullyQualifiedReadType).Append("?) : reader.GetFieldValue<")
                .Append(column.FullyQualifiedReadType).Append(">(ordinals[").Append(ordinalIndex).Append("])");
        }
        else
        {
            builder.Append("reader.GetFieldValue<").Append(column.FullyQualifiedReadType).Append(">(ordinals[")
                .Append(ordinalIndex).Append("])");
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
